[versions]

# ********** App settings **********
packageName = "com.intechbel.techtask"
compileSdk = "35"
minSdk = "24"
targetSdk = "35"
androidGradlePlugin = "8.2.0"
kotlin = "2.0.0"
kotlinSymbolProcessing = "2.0.0-1.0.21"

coroutines = "1.8.1"
chucker = "4.0.0"
retrofit = "2.9.0"
okhttp = "4.12.0"
koin = "3.5.0"
lifecycle = "2.6.2"
desugarJdk = "2.0.4"
serializationJson = "1.8.1"
kotlinxSerializationConverter = "1.0.0"
timber = "5.0.1"
pagingCompose = "3.3.1"
coil = "2.7.0"
activity = "1.8.0"

# ********** Androidx versions **********
browser = "1.8.0"

# ********** JetpackCompose versions **********
compose = "1.6.7"
material3Compose = "1.2.1"
mapsCompose = "4.4.1"
playServicesMaps = "18.1.0"

lottie = "6.1.0"
coreKtx = "1.13.1"

# ********** Google services versions **********
googleServices = "4.4.2"
firebaseCrashlyticsPlugin = "3.0.1"
firebaseCrashlyticsKtx = "19.0.0"

# ********** Test versions **********
mockk = "1.13.17"

# ********** Decompose **********
decompose = "3.4.0"
essenty = "2.5.0"
mvikotlin = "4.3.0"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
retrofitCore = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
kotlinxSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxSerializationConverter" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
koinAndroidCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
coilKtCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
pagingCompose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

#********** Core Library Desugaring **********
desugarJdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdk" }

#********** Androidx libraries **********
browser = { module = "androidx.browser:browser", version.ref = "browser" }

#********** Firebase libraries **********
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }

# ********** JetpackCompose libraries **********
composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "material3Compose" }
composeUI = { module = "androidx.compose.ui:ui", version.ref = "compose" }
toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
mapsCompose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
playServicesMaps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }

livedataRuntime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# ********** Test libraries **********
mockk = { module = "io.mockk:mockk-android", version.ref = "mockk" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koin" }
testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

# ********** Decompose **********
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decomposeJetpackCompose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
essenty = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlinMain = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
mvikotlinExtensionsCoroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }

[bundles]
retrofit = ["retrofitCore", "kotlinxSerializationConverter", "serializationJson", "okhttp", "okhttpInterceptor"]
koin = ["koinAndroidCompose"]
compose = ["composeUI", "toolingPreview", "lottie"]
lifecycle = ["viewmodelKtx", "livedataKtx", "livedataRuntime"]
test = ["mockk", "koinTest", "testManifest"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-symbolProcessing = { id = "com.google.devtools.ksp", version.ref = "kotlinSymbolProcessing" }
